### ISSUE TITLE
Feedback Section 1. Introduction

### ISSUE THREAD

**Issue by avkoehl** [ucdavisdatalab/workshop_web_maps#1]
1.1 

Rather than the “often, the user can pan and zoom …” stuff I would directly define static vs dynamic web map:

*Static map* - An image of map. Can be useful for some applications. Especially for figures that summarize visual information. Since its an image it can easily be rendered by the browser.

[Screenshot of digital map]

*dynamic web map* - What people refer to when they say web map. Links data with an active mapping engine (think google maps). Allows users to interact with the data through zoom, pan, filtering, clicking, hovering… and many other features common in interactive data visualization.  The mapping engine will handle the interactive elements to appropriately display the data. Data is displayed on some base map.

[Animated Gif of dynamic web map]

1.2

Some additional talking points for why make a web map:
- Help tell a narrative about the data
- Its fun to interact with and visualize data in novel ways
- Great for data that is inherently dynamic (many factors, time component)
- Data Validation 
- They are easy to share.
- They are easy to modify and update.
- They are easy to document.

1.3 

I wonder if ParkMobile uses leaflet?

1.5

I would mention that there are several alternatives to Leaflet, but that Leaflet is your preferred open source option. I would also mention that Leaflet has plugins and that there is a package in R for working with Leaflet.

**Comment by MicheleTobias** [comment]
These are all great suggestions! I've incorporated them as much as I can into the text. I'm looking into some more Leaflet examples. ParkMobile uses Google Maps... too bad... that would have been a great example that people on campus are familiar with.
