### ISSUE TITLE
Feedback Section 2. Setting up your file structure

### ISSUE THREAD

**Issue by avkoehl** [ucdavisdatalab/workshop_web_maps#2]
I would rename this section to "Setup".

2.1

In my experience, hosting the data through github (in this repo) and sharing the link to the raw file content is an easy way to share small ish files with the learners. That way you don't need to maintain the data at a different source, don't need to worry about any log in stuff.

You may want to have a preview of the first few lines of the campus_cats.js file and mention that its a text file. You could even take some time to mention what a js file is, and what json is. You probably don't need to explain the difference in the workshop itself, but it may be nice as a note within the reader.

2.3

Typo in the file tree:
`index.htm`

**Comment by MicheleTobias** [comment]
Again, very helpful feedback!  I implemented the text/typo suggestions. I agree that for us it's easier to host everything on the GitHub repo, but it's harder for learners who aren't familiar with GitHub to download data from there.  I've seen many workshops get derailed by this. I will stash a copy of the data in the repo though so we have it all in one place.  I'll address the comment about explaining the data in section 4.3.1 where we talk about the data they're about to use.
