### ISSUE TITLE
Feedback Section 5. Resources

### ISSUE THREAD

**Issue by avkoehl** [ucdavisdatalab/workshop_web_maps#5]
Some additional resources:

Programming Historian walk through: https://programminghistorian.org/en/lessons/mapping-with-python-leaflet

Anatomy of a web map presentation: http://maptime.io/anatomy-of-a-web-map/

Link to leaflet R package: https://rstudio.github.io/leaflet/

Github Pages Documentation: https://docs.github.com/en/pages

**Comment by MicheleTobias** [comment]
Thanks! These are great! I've added them to the resources section.
